### PR TITLE
Fix broken ert test_run

### LINKED ISSUE #8530: ert test_run does not work for non-LOCAL queue systems.
When ert is run on the following:

```
QUEUE_SYSTEM LSF
NUM_REALIZATIONS 1
```

a test_run will crash:

```
$ ert test_run poly.ert
    --> Running forecast for iteration: 0

    1/1 |                                                             |   0% Running time: 2 seconds

    ■ Waiting           1/1
    ■ Pending           0/1
    ■ Running           0/1
    ■ Failed            0/1
    ■ Finished          0/1
    ■ Unknown           0/1

Experiment failed with the following error: Number of active realizations (0) is less than the specified MIN_REALIZATIONS(1)
Traceback (most recent call last):
Unexpected exception in ensemble: 
  File "/data/projects/ert/src/ert/ensemble_evaluator/_ensemble.py", line 246, in _evaluate_inner
    driver = create_driver(self._queue_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected exception in ensemble: 
  File "/data/projects/ert/src/ert/scheduler/__init__.py", line 23, in create_driver
    return LocalDriver(**config.queue_options.driver_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected exception in ensemble: 
TypeError: LocalDriver.__init__() got an unexpected keyword argument 'project_code'
```

This is a regression from #8475

### PR DESCRIPTION
**Pull request by berland**
The commit 4013764 introduced a regression such that `ert test_run` would fail on any configs that sets a queue system other than "local".

This was due to the function `create_local_copy()` not having been updated to yield the correct QueueOptions object after refactoring.

**Issue**
Resolves #8530

**Approach**
:brain:

- [ ] PR title captures the intent of the changes, and is fitting for release notes.
- [x] Added appropriate release note label
- [x] Commit history is consistent and clean, in line with the [contribution guidelines](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md).
- [x] Make sure tests pass locally (after every commit!)

## When applicable
- [ ] **When there are user facing changes**: Updated documentation
- [ ] **New behavior or changes to existing untested code**: Ensured that unit tests are added (See [Ground Rules](https://github.com/equinor/ert/blob/main/CONTRIBUTING.md#ground-rules)).
- [ ] **Large PR**: Prepare changes in small commits for more convenient review
- [ ] **Bug fix**: Add regression test for the bug
- [ ] **Bug fix**: Create Backport PR to latest release

### CODE REVIEW

File: src/ert/config/queue_config.py [hunk 1]
```diff
@@ -360,7 +363,8 @@ def create_local_copy(self) -> QueueConfig:
             self.realization_memory,
             self.max_submit,
             QueueSystem.LOCAL,
-            self.queue_options,
+            self.queue_options_test_run,
```
Comment (xjules) [inline src/ert/config/queue_config.py:366]: This should be just `self.queue_options` I guess.

**Review by eivindjahren — COMMENTED** [review]
Could we maybe have a regression test here where you have a config that uses LSF specific queue options, The queue system is set to LSF, and then you run `ert test_run`? Could probably create something like `test_bad_config_error_message`.

**Comment by berland** [comment]
> Could we maybe have a regression test here where you have a config that uses LSF specific queue options, The queue system is set to LSF, and then you run `ert test_run`? Could probably create something similar to `test_bad_config_error_message`.

Added.

**Review by eivindjahren — APPROVED** [review]
:+1:

File: tests/integration_tests/test_cli.py [hunk 2]
```diff
@@ -41,6 +41,13 @@ def test_bad_config_error_message(tmp_path):
         run_cli(TEST_RUN_MODE, "--disable-monitor", str(tmp_path / "test.ert"))
 
 
+def test_test_run_on_lsf_configuration_works_with_no_errors(tmp_path):
+    (tmp_path / "test.ert").write_text(
+        "NUM_REALIZATIONS 1\nQUEUE_SYSTEM LSF", encoding="utf-8"
```
Comment (eivindjahren) [inline tests/integration_tests/test_cli.py:46]: Maybe just add one `QUEUE_OPTION LSF PROJECT PROJECT` to make sure we populate some incompatible options.

Comment (berland) [reply tests/integration_tests/test_cli.py:46]: The options were not really part of the problem in this bug. There are other tests asserting which errors or warnings arise when incompatible options are supplied, I think they suffice.
