### ISSUE TITLE
ert test_run does not work for non-LOCAL queue systems.

### ISSUE THREAD

**Issue by berland** [equinor/ert#8530]
When ert is run on the following:

```
QUEUE_SYSTEM LSF
NUM_REALIZATIONS 1
```

a test_run will crash:

```
$ ert test_run poly.ert
    --> Running forecast for iteration: 0

    1/1 |                                                             |   0% Running time: 2 seconds

    ■ Waiting           1/1
    ■ Pending           0/1
    ■ Running           0/1
    ■ Failed            0/1
    ■ Finished          0/1
    ■ Unknown           0/1

Experiment failed with the following error: Number of active realizations (0) is less than the specified MIN_REALIZATIONS(1)
Traceback (most recent call last):
Unexpected exception in ensemble: 
  File "/data/projects/ert/src/ert/ensemble_evaluator/_ensemble.py", line 246, in _evaluate_inner
    driver = create_driver(self._queue_config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected exception in ensemble: 
  File "/data/projects/ert/src/ert/scheduler/__init__.py", line 23, in create_driver
    return LocalDriver(**config.queue_options.driver_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unexpected exception in ensemble: 
TypeError: LocalDriver.__init__() got an unexpected keyword argument 'project_code'
```

This is a regression from #8475
